<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <!-- <header> -->
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <a class="navbar-brand" href="/">Главная</a>
        <a class="navbar-brand" href="/urls">Сайты</a>
    </nav>
    </header>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <div class="row">
                <h1>Сайты</h1>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                    <?php foreach ($urls as $url): ?>
                        <tr>
                            <td><?= $url['id'] ?></td>
                            <td><?= $url['name'] ?></td>
                            <td><?= $url['last_check'] ?></td>
                            <td><?= $url['status_code'] ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                </table>
        </div>
        </div>
        <!-- <p class="lead"><?= $url ?></p> -->
    </main>
    <footer class="footer fixed-bottom">
    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        <a class="text-dark" href="https://hh.ru/resume/f725e2a8ff0b8b579b0039ed1f30776a424c72">© 2023 Ясинский Сергей Анатольевич</a>
    </div>
    </footer>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> -->
</body>
</html>