<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body class="min-vh-100">
    <!-- <header> -->
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <a class="navbar-brand" href="/">Главная</a>
        <a class="navbar-brand" href="/urls">Сайты</a>
    </nav>
    </header>
    <main class="flex-grow-1">
        <?php if (isset($flash)): ?>
            <?php foreach ($flash as $messages): ?>
                <?php foreach ($messages as $message): ?>
                <div class="alert alert-success" role="alert">
                    <?= htmlspecialchars($message) ?>
                </div>
                <?php endforeach ?>
            <?php endforeach ?>
        <?php endif ?>
        <div class="container-lg mt-3">
            <h1>Сайт: <?= $url['name'] ?></h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                    <td>ID</td>
                    <td><?= $url['id'] ?></td>
                    </tr>
                    <tr>
                    <td>Имя</td>
                    <td><?= $url['name'] ?></td>
                    </tr>
                    <tr>
                    <td>Дата создания</td>
                    <td><?= $url['created_at'] ?></td>
                    </tr>
                </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="<?= "/urls/{$url['id']}/checks"?>">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                    <?php foreach ($checks as $check): ?>
                    <tr>
                        <td><?= $check['id'] ?></td>
                        <td><?= $check['status_code'] ?></td>
                        <td class="text-break"><?= $check['h1'] ?></td>
                        <td class="text-break"><?= $check['title'] ?></td>
                        <td class="text-break"><?= $check['description'] ?></td>
                        <td><?= $check['created_at'] ?></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <!-- <p class="lead"><?= $url ?></p> -->
    </main>
    <footer class="footer fixed-bottom">
    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        <a class="text-dark" href="https://hh.ru/resume/f725e2a8ff0b8b579b0039ed1f30776a424c72">© 2023 Ясинский Сергей Анатольевич</a>
    </div>
    </footer>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> -->
</body>
</html>