<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="site analyst">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body class="min-vh-100 d-flex flex-column">
    <!-- <header> -->
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <a class="navbar-brand" href="/">Главная</a>
        <a class="navbar-brand" href="/urls">Сайты</a>
    </nav>
    </header>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <?php if (isset($flash)): ?>
                        <?php foreach ($flash as $messages): ?>
                            <?php foreach ($messages as $message): ?>
                            <div class="alert alert-success" role="alert">
                                <?= htmlspecialchars($message) ?>
                            </div>
                            <?php endforeach ?>
                        <?php endforeach ?>
                    <?php endif ?>
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method="post" class="row" required="">
                        <div class="col-8">
                        <input type="text" name="url[name]" value="" class="form-control form-control-lg" placeholder="https://www.example.com">
                        </div>
                        <?php if (isset($errors)): ?>
                        <div>Некорректный URL</div>
                        <?php endif ?>
                        <div class="col-2">
                            <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- <p class="lead"><?= $url ?></p> -->
    </main>
    <footer class="footer border-top py-3 mt-5 flex-shrink-0">
    <!-- <footer class="footer fixed-bottom"> -->
    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        <a class="text-dark" href="https://hh.ru/resume/f725e2a8ff0b8b579b0039ed1f30776a424c72">© 2023 Ясинский Сергей Анатольевич</a>
    </div>
    </footer>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> -->
</body>
</html>